object Versions {

    const val ROOM_VERSION = "2.5.2"
    const val GLIDE_VERSION = "4.14.2"
    const val VIEWPAGER_VERSION = "1.0.0"
    const val FEATURES_VERSION = "2.7.1"
    const val SCOPE_VERSION = "2.4.0"
    const val RETROFIT = "2.9.0"
    const val COROUTINES_VERSION = "1.3.9"
    const val FRAGMENT_VERSION = "1.5.7"
    const val CORE_KTX = "1.10.1"
    const val APP_COMPAT = "1.6.1"
    const val MATERIAL = "1.9.0"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val JUNIT = "4.13.2"
    const val ANDROIDX_TEST_JUNIT = "1.1.5"
    const val ESPRESSO_CORE = "3.5.1"
    const val HILT = "2.44"
    const val NAV_VERSION = "2.7.0"
    const val LIFECYCLE_VERSION = "2.6.1"
}